components:
  schemas:
    JWT:
      properties:
        token:
          title: Token
          type: string
      required:
      - token
      title: JWT
      type: object
info:
  description: Proof of Concept API
  title: POC API
  version: 1.0.0
openapi: 3.1.0
paths:
  /api/open_api.json:
    get:
      description: Retrieve the generated OpenAPI schema in JSON format.
      operationId: get_openapi_json_api_open_api_json_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Openapi Json
  /api/open_api.yaml:
    get:
      description: Retrieve the generated OpenAPI schema in YAML format.
      operationId: get_openapi_yaml_api_open_api_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Openapi Yaml
  /api/v1/auth:
    get:
      description: Get the JWT token for Google Cloud Speech-to-Text API
      operationId: get_auth_api_v1_auth_get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
          description: Successful Response
      summary: Get Auth
