version: '3.8'

services:
  stream-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8083:8083"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 